config/routes.rb
Rails.application.routes.draw do
 
  get 'about' => 'welcome#about'

  devise_for :users
    root to: "welcome#index" || "users#show"

  resources :users, only: [:show] do
    resources :items, only: [:create, :destroy]
  end

end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :user

	# default_scope { order('created_at DESC')}

	validates :body, length: { minimum: 10}, presence: true
	validates :completed, :inclusion => {:in => [true, false]}
	validates :user, presence: true
	
	def days_left
		7 - ((DateTime.now.to_date - created_at.to_date).to_i)
	end



end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :items


	# def avatar_url(size)
	# 	gravatar_id = Digest::MD5::hexdigest(self.email).downcase
	# 	"http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
	# end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

	def after_sign_in_path_for(resource)
	   # request.env['omniauth.origin'] || stored_location_for(resource) || root_path
	   user_path(resource)
	end

  protected

	def configure_permitted_parameters
	  devise_parameter_sanitizer.for(:sign_up) << :name
	end
 
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_filter :set_fake_flash

  # def index
  #   @items = Item.all
  # end

  def new
    @item = Item.new
  end

  # def show
  #   @item = Item.find(params[:id])
  # end

  def create
    @user = current_user
    @item = @user.items.build(item_params)

    if @item.save
      flash[:notice] = "Item was saved."
    else
      flash.now[:alert] = "There was an error saving the item."
    end
     redirect_to user_path(@user)
  end

  # def update
  # end

  def destroy
    @user = current_user
    @item = @user.items.find(params[:id])

    if @item.destroy
      @flash[:notice] = "Item was completed!"
    else
      @flash[:error] = "There was an error deleting the item."
    end

    respond_to do |format|
      format.html
      format.js
    end
  end


  private

  def item_params
    params.require(:item).permit(:body, :completed)
  end

  def set_fake_flash
    @flash = {}
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
  	@user = current_user || User.find(params[:id])
	# @user = User.find(params[:id]) 
	@items = @user.items
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  skip_before_filter :authenticate_user!
  
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def avatar_url(user)
		gravatar_id = Digest::MD5::hexdigest(user.email).downcase
		"http://gravatar.com/avatar/#{gravatar_id}.png?s=48"
	end
end

app/helpers/items_helper.rb
module ItemsHelper


end

app/helpers/sessions_helper.rb
module SessionsHelper

	# def create_session(user)
	# 	session[:user_id] = user.id
	# end

	# def destroy_session(user)
	# 	session[:user_id] = nil
	# end


	# def current_user
	# 	User.find_by(id: session[:user_id])
	# end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<%= form_for [user, item] do |f| %>

	<div class="form-group">
		<%= f.label :body %>
		<%= f.text_field :body, rows: 4, class: 'form-control', placeholder: "Enter to-do list item." %>
		<%= f.submit "Save Item", class: 'btn btn-success' %>
	</div>

<% end %>

app/views/items/_item.html.erb
<div class="media">
	<div class="media-body">
		<div class="table-responsive">
			<table class="table">
				<thead>
					<tr>
						<th>Item</th>
						<th>Days Left</th>
						<th>Completed</th>
					</tr>
				</thead>
				<tbody>
						<% @user.items.each do |item| %> <br/>
							<tr id="item-<%= item.id %>">
								<td><%= item.body %></td>
								<td><%= item.days_left %> days left </td>
								<td><%= link_to "", user_item_path({user_id: current_user.id, id: item.id}), method: :delete, remote: true, class: 'glyphicon glyphicon-ok' %></td>
							<% end %>
						
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

app/views/items/destroy.html.erb
<h1>Items#destroy</h1>
<p>Find me in app/views/items/destroy.html.erb</p>

app/views/items/destroy.js.erb
<% if @item.destroyed? %>
	$('#item-<%= @item.id %>').hide();
	$('.js-items-count').html("<%= pluralize(current_user.items.count, 'item') %> left");
	$('.flash').html("<div class='alert alert-success'><%= @flash[:notice] %></div>");
<% else %>
	$('.flash').html("<div class='alert alert-danger'><%= @flash[:error] %></div>");
<% end %>

app/views/items/index.html.erb
<h1>To Do List Items</h1>
<% @items.each do |item| %>
<div class="media">
	<div class="media-body">
		<h4 class="media-heading">
			<%= link_to item.body, item %>
			<%= link_to item.completed, item %>
		</h4>
	</div>
</div>
<% end %>

app/views/items/new.html.erb
<h1>New Item</h1>

<div class="row">
	<div class="col-md-8">
		<p>Add your to-do item here:</p>
		
		<%= render partial: 'form', locals: { item: @item } %>

	</div>
</div>

app/views/items/show.html.erb
<h1><%= @item.body %></h1>
<p><%= @item.completed %> </h1>

app/views/items/update.html.erb
<h1>Items#update</h1>
<p>Find me in app/views/items/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bloccitoff</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
	<ul class="nav nav-tabs">
		<li><%= link_to "Home", root_path %></li>
		<li><%= link_to "About", about_path %></li>
		<li><%= link_to "My Items", user_path(current_user) %></li>
	</ul>

<div class="flash">
	<% if flash[:notice] %>
		<div class="alert alert-success">
			<button type="button" class="close" data-dismiss="alert">&times;</button>
			<%= flash[:notice] %>
		</div>
	<% elsif flash.now[:alert] %>
		<div class="alert alert-danger">
			<button type="button" class="close" data-dismiss="alert">&times;</button>
			<%= flash.now[:alert] %>
		</div>
	<% elsif flash[:alert] %>
		<div class="alert alert-warning">
			<button type="button" class="close" data-dismiss="alert">&times;</button>
			<%= flash[:alert] %>
		</div>
	<% end %>
</div>

<div class="container">

	<% if user_signed_in? %>
	<%= image_tag avatar_url(current_user), class: "gravatar" %>
	Signed in as: <strong><%= current_user.email %></strong> | 
	<%= link_to 'Edit Profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
	<% else %>
	<%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link' %>
	<% end %>
	
</div>

<%= yield %>
</div>

</body>
</html>

app/views/users/show.html.erb
<div class="row">
	<div class="col-md-8">
		<div class="media">
			<br/>
			<div class="media-body">
				<h2 class="media-heading"><%= current_user.name %></h2>
				<medium>
					<div class='js-items-count'><%= pluralize(current_user.items.count, 'item') %></div>
				</medium>
			</div>	
		</div>		
	</div>
</div>

<h3>To Do Items</h3>
	<%= render partial: 'items/item', locals: { item: @item, user: current_user } %>

<h3>Add New To-Do Item</h3>
<% if current_user %>
	<%= render partial: 'items/form', locals: { item: Item.new, user: current_user } %>
<% end %>

app/views/welcome/about.html.erb
<h1>Bloccitoff</h1>
<p>A web application designed to keep your to-do list organized by automatically removing the items that have not been completed in 7 days.</p>

app/views/welcome/index.html.erb
<div class="container">
	<h1>Welcome to Bloccitoff</h1>
	<p>Has your to-do list become long and unmanageable?</p>
	<p>Bloccitoff is a tool to help keep your to-do list prioritized and organized so you only tackle what's important.</p>
</div>